version: '3'
services:
  zookeeper1:
    restart: always
    image: confluentinc/cp-zookeeper
    container_name: zookeeper1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888
    ports:
      - '12181:2181'
    mem_limit: 1g

  zookeeper2:
    restart: always
    image: confluentinc/cp-zookeeper
    container_name: zookeeper2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEPER_SERVER_ID: 2
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888
    ports:
      - '12182:2181'
    mem_limit: 1g
